services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
    - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}